variables:
  SKIP_TESTS: "false"

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  before_script:
    - ruby -v
    - gem install bundler -v 2.0.2
    - bundle version
  script:
    - cp $RAILS_DEPLOY_PATH/etc/database.yml config/
    - cp $RAILS_DEPLOY_PATH/etc/analytics.yml config/
    - cp $RAILS_DEPLOY_PATH/etc/browse_everything_providers.yml config/
    - bundle _2.0.2_ install --path=vendor/bundle --without=development --binstubs=bin --no-cache
    - bundle binstubs bundler --force
    - bundle exec rake assets:precompile
  artifacts:
    paths:
      - .bundle/
      - bin/
      - config/database.yml
      - config/analytics.yml
      - config/browse_everything_providers.yml
      - public/assets/
      - vendor/bundle/
  tags:
    - build

.test:
  stage: test
  variables:
    RAILS_ENV: test
  before_script:
    - source $RAILS_DEPLOY_PATH/etc/export-test.env
    - ruby -v
    - bundle version
    - node -v
    - psql --version
    - $FITS_PATH -v
    - $BLENDER_PATH/blender -v
    - img2dcm --version
    - dcmdjpeg --version
    - gltf-pipeline --version
    - bin/rake db:reset
    - bundle exec rake morphosource:create_collection_types
  tags:
    - test

test_until_fail_job:
  extends: .test
  variables: 
    RSPEC_FAIL_FAST: "true"
  except:
    refs: 
      - main
    variables:
      - $SKIP_TESTS == "true"
  script:
    - bin/rake ci:wrapped_spec[~accessibility]

test_all_job:
  extends: .test
  except: 
    variables:
      - $SKIP_TESTS == "true"
  only:
    - main
  script:
    - bin/rake ci:wrapped_spec[~accessibility]

accessibility_job:
  extends: .test
  except: 
    variables:
      - $SKIP_TESTS == "true"
  allow_failure: true
  script:
    - bin/rake ci:wrapped_spec[accessibility]

.deploy:
  stage: deploy
  variables:
    RAKE_COMMAND: sudo -u $RAILS_USER -n -i $RAILS_ROOT/bin/rake -f $RAILS_ROOT/Rakefile
  script:
    - rsync -rl --delete --exclude-from=EXCLUDE ./ $RAILS_ROOT/
    - '$RAKE_COMMAND db:setup || true'
    - $RAKE_COMMAND db:migrate
    - $RAKE_COMMAND tmp:cache:clear
    - $RAKE_COMMAND hyrax:workflow:load
  after_script:
    - sudo /usr/bin/systemctl restart $RAILS_SERVICE_UNIT

deploy_dev:
  extends: .deploy
  environment:
    name: development
    url: https://morphosource-dev.oit.duke.edu/
  only:
    - dev
  tags:
    - development

deploy_prod:
  extends: .deploy
  environment:
    name: production
    url: https://www.morphosource.org/
  only:
    - main
  tags:
    - production
