variables:
  MIGRATE_DB: "false"
  SKIP_TESTS: "false"
  SPLIT_TESTS: "true"

stages:
  - build
  - test
  - predeploy
  - deploy

.build:
  stage: build
  image: docker:27
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    DOCKER_CLI_EXPERIMENTAL: enabled
  services:
    - name: docker:27-dind
  before_script:
    - echo "$CONTAINER_REGISTRY_TOKEN_GITLAB" | docker login -u containerwrite --password-stdin gitlab-registry.oit.duke.edu
  tags:
    - oit-shared

build_app:
  extends: .build
  script:
    - APP_IMAGE="gitlab-registry.oit.duke.edu/morphosource/morphosource:app-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
    - if docker manifest inspect "$APP_IMAGE" > /dev/null 2>&1; then echo "Image $APP_IMAGE already exists. Skipping build."; exit 0; fi
    - docker build --target morphosource-prod --tag gitlab-registry.oit.duke.edu/morphosource/morphosource:app-$CI_COMMIT_BRANCH --tag "$APP_IMAGE"  .
    - docker push "$APP_IMAGE"
    - docker push gitlab-registry.oit.duke.edu/morphosource/morphosource:app-$CI_COMMIT_BRANCH

build_worker:
  extends: .build
  script:
    - WORKER_IMAGE="gitlab-registry.oit.duke.edu/morphosource/morphosource:worker-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA"
    - if docker manifest inspect "$WORKER_IMAGE" > /dev/null 2>&1; then echo "Image $WORKER_IMAGE already exists. Skipping build."; exit 0; fi
    - docker build --target morphosource-worker-prod --tag gitlab-registry.oit.duke.edu/morphosource/morphosource:worker-$CI_COMMIT_BRANCH --tag "$WORKER_IMAGE"  .
    - docker push "$WORKER_IMAGE"
    - docker push gitlab-registry.oit.duke.edu/morphosource/morphosource:worker-$CI_COMMIT_BRANCH

test:
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    RAILS_ENV: test
  except:
    variables:
      - $SKIP_TESTS == "true"
      - $SPLIT_TESTS == "true"
  services:
    - name: docker:20.10-dind
  needs:
    - build_worker
  before_script:
    - echo "$CONTAINER_REGISTRY_TOKEN_GITLAB" | docker login -u containerwrite --password-stdin gitlab-registry.oit.duke.edu
  script:
    - docker network create test-network
    - docker run --name postgres --network test-network -e POSTGRES_USER=hydra -e POSTGRES_PASSWORD=hydra -e POSTGRES_DB=test -d postgres
    - docker run --name solr --network test-network -v $(pwd)/solr/conf:/core_config/conf -d solr:7.7.3 sh -c "solr-precreate hydra-test /core_config"
    - docker run --name fcrepo --network test-network -v $(pwd)/vendor/docker/fcrepo/fedora.xml:/var/lib/jetty/webapps/fedora.xml -d ghcr.io/samvera/fcrepo4:4.7.5
    - docker run --name redis --network test-network -d redis:5-alpine
    - docker run --name morphosource --network test-network --env-file ./vendor/docker/docker-compose.env -e RAILS_ENV=test -e SOLR_TEST_URL=http://solr:8983/solr/hydra-test -e FCREPO_BASE_PATH=/test -e FIJI_SCRIPT_COMMAND= gitlab-registry.oit.duke.edu/morphosource/morphosource:worker-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA docker-test.sh
  tags:
    - oit-shared

test_controllers:
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    RAILS_ENV: test
  except:
    variables:
      - $SKIP_TESTS == "true"
      - $SPLIT_TESTS == "false"
  services:
    - name: docker:20.10-dind
  needs:
    - build_worker
  before_script:
    - echo "$CONTAINER_REGISTRY_TOKEN_GITLAB" | docker login -u containerwrite --password-stdin gitlab-registry.oit.duke.edu
  script:
    - docker network create test-network
    - docker run --name postgres --network test-network -e POSTGRES_USER=hydra -e POSTGRES_PASSWORD=hydra -e POSTGRES_DB=test -d postgres
    - docker run --name solr --network test-network -v $(pwd)/solr/conf:/core_config/conf -d solr:7.7.3 sh -c "solr-precreate hydra-test /core_config"
    - docker run --name fcrepo --network test-network -v $(pwd)/vendor/docker/fcrepo/fedora.xml:/var/lib/jetty/webapps/fedora.xml -d ghcr.io/samvera/fcrepo4:4.7.5
    - docker run --name redis --network test-network -d redis:5-alpine
    - docker run --name morphosource --network test-network --env-file ./vendor/docker/docker-compose.env -e RAILS_ENV=test -e SOLR_TEST_URL=http://solr:8983/solr/hydra-test -e FCREPO_BASE_PATH=/test -e FIJI_SCRIPT_COMMAND= -e TEST_GROUP=1 gitlab-registry.oit.duke.edu/morphosource/morphosource:worker-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA docker-test.sh
  tags:
    - oit-shared

test_actors_to_lib:
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    RAILS_ENV: test
  except:
    variables:
      - $SKIP_TESTS == "true"
      - $SPLIT_TESTS == "false"
  services:
    - name: docker:20.10-dind
  needs:
    - build_worker
  before_script:
    - echo "$CONTAINER_REGISTRY_TOKEN_GITLAB" | docker login -u containerwrite --password-stdin gitlab-registry.oit.duke.edu
  script:
    - docker network create test-network
    - docker run --name postgres --network test-network -e POSTGRES_USER=hydra -e POSTGRES_PASSWORD=hydra -e POSTGRES_DB=test -d postgres
    - docker run --name solr --network test-network -v $(pwd)/solr/conf:/core_config/conf -d solr:7.7.3 sh -c "solr-precreate hydra-test /core_config"
    - docker run --name fcrepo --network test-network -v $(pwd)/vendor/docker/fcrepo/fedora.xml:/var/lib/jetty/webapps/fedora.xml -d ghcr.io/samvera/fcrepo4:4.7.5
    - docker run --name redis --network test-network -d redis:5-alpine
    - docker run --name morphosource --network test-network --env-file ./vendor/docker/docker-compose.env -e RAILS_ENV=test -e SOLR_TEST_URL=http://solr:8983/solr/hydra-test -e FCREPO_BASE_PATH=/test -e FIJI_SCRIPT_COMMAND= -e TEST_GROUP=2 gitlab-registry.oit.duke.edu/morphosource/morphosource:worker-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA docker-test.sh
  tags:
    - oit-shared

test_models:
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    RAILS_ENV: test
  except:
    variables:
      - $SKIP_TESTS == "true"
      - $SPLIT_TESTS == "false"
  services:
    - name: docker:20.10-dind
  needs:
    - build_worker
  before_script:
    - echo "$CONTAINER_REGISTRY_TOKEN_GITLAB" | docker login -u containerwrite --password-stdin gitlab-registry.oit.duke.edu
  script:
    - docker network create test-network
    - docker run --name postgres --network test-network -e POSTGRES_USER=hydra -e POSTGRES_PASSWORD=hydra -e POSTGRES_DB=test -d postgres
    - docker run --name solr --network test-network -v $(pwd)/solr/conf:/core_config/conf -d solr:7.7.3 sh -c "solr-precreate hydra-test /core_config"
    - docker run --name fcrepo --network test-network -v $(pwd)/vendor/docker/fcrepo/fedora.xml:/var/lib/jetty/webapps/fedora.xml -d ghcr.io/samvera/fcrepo4:4.7.5
    - docker run --name redis --network test-network -d redis:5-alpine
    - docker run --name morphosource --network test-network --env-file ./vendor/docker/docker-compose.env -e RAILS_ENV=test -e SOLR_TEST_URL=http://solr:8983/solr/hydra-test -e FCREPO_BASE_PATH=/test -e FIJI_SCRIPT_COMMAND= -e TEST_GROUP=3 gitlab-registry.oit.duke.edu/morphosource/morphosource:worker-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA docker-test.sh
  tags:
    - oit-shared

test_presenters_to_vocabularies:
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    RAILS_ENV: test
  except:
    variables:
      - $SKIP_TESTS == "true"
      - $SPLIT_TESTS == "false"
  services:
    - name: docker:20.10-dind
  needs:
    - build_worker
  before_script:
    - echo "$CONTAINER_REGISTRY_TOKEN_GITLAB" | docker login -u containerwrite --password-stdin gitlab-registry.oit.duke.edu
  script:
    - docker network create test-network
    - docker run --name postgres --network test-network -e POSTGRES_USER=hydra -e POSTGRES_PASSWORD=hydra -e POSTGRES_DB=test -d postgres
    - docker run --name solr --network test-network -v $(pwd)/solr/conf:/core_config/conf -d solr:7.7.3 sh -c "solr-precreate hydra-test /core_config"
    - docker run --name fcrepo --network test-network -v $(pwd)/vendor/docker/fcrepo/fedora.xml:/var/lib/jetty/webapps/fedora.xml -d ghcr.io/samvera/fcrepo4:4.7.5
    - docker run --name redis --network test-network -d redis:5-alpine
    - docker run --name morphosource --network test-network --env-file ./vendor/docker/docker-compose.env -e RAILS_ENV=test -e SOLR_TEST_URL=http://solr:8983/solr/hydra-test -e FCREPO_BASE_PATH=/test -e FIJI_SCRIPT_COMMAND= -e TEST_GROUP=4 gitlab-registry.oit.duke.edu/morphosource/morphosource:worker-$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA docker-test.sh
  tags:
    - oit-shared

# Defunct, TODO consider reimplementing in future
# predeploy_prod:
#   stage: predeploy
#   environment:
#     name: production
#     url: https://www.morphosource.org/
#   variables:
#     RAKE_COMMAND: sudo -u $RAILS_USER -n -i $RAILS_ROOT/bin/rake -f $RAILS_ROOT/Rakefile
#   only:
#     refs:
#       - main
#     variables:
#       - $FAST_DEPLOY == "false"
#   allow_failure: true
#   script:
#     - $RAKE_COMMAND morphosource:set_time_until_maintenance_in_minutes[30]
#   tags:
#     - production

.deploy:
  stage: deploy
  variables:
    K8S_STRATEGY: RollingUpdate
    K8S_RUN_DB_MIGRATE: false
  image:
    name: gitlab-registry.oit.duke.edu/duke_openshift_users/community-supported-resources/build-helper:alpine
  tags:
    - oit-shared

deploy_dev:
  extends: .deploy
  only:
    refs:
      - dev
  before_script:
    - if [ "$MIGRATE_DB" == "true" ]; then K8S_STRATEGY="Recreate"; fi
    - if [ "$MIGRATE_DB" == "true" ]; then K8S_RUN_DB_MIGRATE="true"; fi
    - oc login $K8S_URL_DEV --token=$K8S_TOKEN_DEV
    - oc project $K8S_NAMESPACE_DEV
  script:
    - mkdir helm_chart
    - cd helm_chart/
    - git clone https://$GITLAB_CI_REPO_READ_USER:$GITLAB_CI_REPO_READ_TOKEN@gitlab.oit.duke.edu/morphosource/helm-chart.git .
    - helm upgrade morphosource charts/hyrax -f charts/hyrax/values.yaml -f charts/hyrax/values.dev.yaml --set image.tagPrefix=app-dev- --set worker.image.tagPrefix=worker-dev- --set workerBatch.image.tagPrefix=worker-dev- --set workerHeavy.image.tagPrefix=worker-dev- --set image.tagVersion=$CI_COMMIT_SHORT_SHA --set strategyType=$K8S_STRATEGY --set runDbMigrate=$K8S_RUN_DB_MIGRATE

deploy_prod:
  extends: .deploy
  only:
    refs:
      - main
  before_script:
    - if [ "$MIGRATE_DB" == "true" ]; then K8S_STRATEGY="Recreate"; fi
    - if [ "$MIGRATE_DB" == "true" ]; then K8S_RUN_DB_MIGRATE="true"; fi
    - oc login $K8S_URL_PROD --token=$K8S_TOKEN_PROD
    - oc project $K8S_NAMESPACE_PROD
  script:
    - mkdir helm_chart
    - cd helm_chart/
    - git clone https://$GITLAB_CI_REPO_READ_USER:$GITLAB_CI_REPO_READ_TOKEN@gitlab.oit.duke.edu/morphosource/helm-chart.git .
    - helm upgrade morphosource charts/hyrax -f charts/hyrax/values.yaml -f charts/hyrax/values.prod.yaml --set image.tagPrefix=app-main- --set worker.image.tagPrefix=worker-main- --set workerBatch.image.tagPrefix=worker-main- --set workerHeavy.image.tagPrefix=worker-main- --set image.tagVersion=$CI_COMMIT_SHORT_SHA --set strategyType=$K8S_STRATEGY --set runDbMigrate=$K8S_RUN_DB_MIGRATE
