variables:
  FAST_DEPLOY: "false"
  SKIP_TESTS: "false"

stages:
  - build
  - test
  - predeploy
  - deploy

build_job:
  stage: build
  except:
    refs: 
      - k8s
  before_script:
    - ruby -v
    - gem install bundler -v 2.0.2
    - bundle version
  script:
    - cp $RAILS_DEPLOY_PATH/etc/database.yml config/
    - cp $RAILS_DEPLOY_PATH/etc/analytics.yml config/
    - cp $RAILS_DEPLOY_PATH/etc/browse_everything_providers.yml config/
    - bundle _2.0.2_ install --path=vendor/bundle --without=development --binstubs=bin --no-cache
    - bundle binstubs bundler --force
    - bundle exec rake assets:precompile
  artifacts:
    paths:
      - .bundle/
      - bin/
      - config/database.yml
      - config/analytics.yml
      - config/browse_everything_providers.yml
      - public/assets/
      - vendor/bundle/
  tags:
    - build

build_container_job:
  stage: build
  only:
    - k8s
  script:
    - echo "$CONTAINER_REGISTRY_TOKEN" | docker login -u juliewinchester --password-stdin
    - docker build --target morphosource --tag juliewinchester/morphosource:app-dev-$CI_COMMIT_SHORT_SHA .
    - docker push juliewinchester/morphosource:app-dev-0.0.23 
    - docker build --target ms-worker --tag juliewinchester/morphosource:worker-dev-$CI_COMMIT_SHORT_SHA .
    - docker push juliewinchester/morphosource:worker-dev-0.0.23 
  tags:
    - oit-shared

.test:
  stage: test
  variables:
    RAILS_ENV: test
  except:
    refs: 
      - k8s
  before_script:
    - source $RAILS_DEPLOY_PATH/etc/export-test.env
    - ruby -v
    - bundle version
    - node -v
    - psql --version
    - $BLENDER_PATH/blender -v
    - $FIJI_PATH/Fiji.app/ImageJ-linux64 --info
    - $FITS_PATH -v
    - $MORPHOSOURCE_PYTHON --version
    - img2dcm --version
    - dcmdjpeg --version
    - gltf-pipeline --version
    - bin/rake db:reset
    - bundle exec rake morphosource:create_collection_types
  tags:
    - test

test_until_fail_job:
  extends: .test
  variables: 
    RSPEC_FAIL_FAST: "true"
  except:
    refs: 
      - main
    variables:
      - $SKIP_TESTS == "true"
  script:
    - bin/rake ci:wrapped_spec[~accessibility]

test_all_job:
  extends: .test
  except: 
    variables:
      - $SKIP_TESTS == "true"
  only:
    - main
  script:
    - bin/rake ci:wrapped_spec[~accessibility]

accessibility_job:
  extends: .test
  except: 
    variables:
      - $SKIP_TESTS == "true"
  allow_failure: true
  script:
    - bin/rake ci:wrapped_spec[accessibility]

predeploy_prod:
  stage: predeploy
  environment:
    name: production
    url: https://www.morphosource.org/
  variables:
    RAKE_COMMAND: sudo -u $RAILS_USER -n -i $RAILS_ROOT/bin/rake -f $RAILS_ROOT/Rakefile
  only:
    refs:
      - main
    variables:
      - $FAST_DEPLOY == "false"
  allow_failure: true
  script:
    - $RAKE_COMMAND morphosource:set_time_until_maintenance_in_minutes[30]
  tags:
    - production

.deploy:
  stage: deploy
  variables:
    RAKE_COMMAND: sudo -u $RAILS_USER -n -i $RAILS_ROOT/bin/rake -f $RAILS_ROOT/Rakefile
  except:
    refs: 
      - k8s
  script:
    - rsync -rl --delete --exclude-from=EXCLUDE ./ $RAILS_ROOT/
    - $RAKE_COMMAND maintenance:start
    - '$RAKE_COMMAND db:setup || true'
    - $RAKE_COMMAND db:migrate
    - $RAKE_COMMAND tmp:cache:clear
    - $RAKE_COMMAND hyrax:workflow:load
    - $RAKE_COMMAND morphosource:clear_time_until_maintenance_in_minutes
    - $RAKE_COMMAND maintenance:end
  after_script:
    - sudo /usr/bin/systemctl restart $RAILS_SERVICE_UNIT

deploy_dev:
  extends: .deploy
  environment:
    name: development
    url: https://morphosource-dev.oit.duke.edu/
  only:
    refs:
      - dev
  tags:
    - development

deploy_prod:
  extends: .deploy
  environment:
    name: production
    url: https://www.morphosource.org/
  only:
    refs:
      - main
    variables: 
      - $FAST_DEPLOY == "false"
  when: delayed
  start_in: 30 minutes
  tags:
    - production

fast_deploy_prod:
  stage: deploy
  environment:
    name: production
    url: https://www.morphosource.org/
  variables:
    RAKE_COMMAND: sudo -u $RAILS_USER -n -i $RAILS_ROOT/bin/rake -f $RAILS_ROOT/Rakefile
  only:
    refs:
      - main
    variables: 
      - $FAST_DEPLOY == "true"
  script:
    - rsync -rl --delete --exclude-from=EXCLUDE ./ $RAILS_ROOT/
    - '$RAKE_COMMAND db:setup || true'
    - $RAKE_COMMAND db:migrate
    - $RAKE_COMMAND tmp:cache:clear
    - $RAKE_COMMAND hyrax:workflow:load
  after_script:
    - sudo /usr/bin/systemctl restart $RAILS_SERVICE_UNIT
  tags:
    - production
