# Based on https://github.com/duke-libraries/rdr/blob/develop/.travis.yml

matrix:
  include:
    - language: python
      python: 
        - 3.5

      before_install:

        # begin installing Alembic python dependencies --------
        - python -V



        - cd $TRAVIS_BUILD_DIR
      before_script:


      script: 
        - python -V
