version: '3.7'

services:
  app: &app
    build:
      context: .
      target: morphosource
      args:
        - EXTRA_APK_PACKAGES=git less
    container_name: app
    command: sh -c 'bundle && bundle exec puma -v -b tcp://0.0.0.0:3000'
    stdin_open: true
    tty: true
    user: app
    env_file:
      - ./vendor/docker/credentials.env
      - ./vendor/docker/docker-compose.env
    depends_on:
      - db_migrate
      - fcrepo
      - memcached
      - postgres
      - redis
      - solr
    ports:
      - 3000:3000
    volumes:
      - .:/app/samvera/hyrax-webapp
      - hyrax-derivatives:/app/samvera/hyrax-webapp/derivatives
      - hyrax-uploads:/app/samvera/hyrax-webapp/uploads
      - rails-public:/app/samvera/hyrax-webapp/public
      - rails-tmp:/app/samvera/hyrax-webapp/tmp
    networks:
      - morphosource

  app_worker:
    build:
      context: .
      target: msworker
    container_name: app_worker
    command: sh -c 'bundle && QUEUE=* bundle exec rails resque:workers'
    user: app
    env_file:
      - ./vendor/docker/credentials.env
      - ./vendor/docker/docker-compose.env
    depends_on:
      - db_migrate
      - fcrepo
      - memcached
      - postgres
      - redis
      - solr
    volumes:
      - .:/app/samvera/hyrax-webapp
      - hyrax-derivatives:/app/samvera/hyrax-webapp/derivatives
      - hyrax-uploads:/app/samvera/hyrax-webapp/uploads
      - rails-public:/app/samvera/hyrax-webapp/public
      - rails-tmp:/app/samvera/hyrax-webapp/tmp
    networks:
      - morphosource

  app_test:
    build:
      context: .
      target: msworker
    container_name: app_test
    command: sh -c 'rm -rf /app/samvera/hyrax-webapp/tmp/* && bundle && bundle exec rake hydra:test_server'
    user: app
    env_file:
      - ./vendor/docker/credentials.env
      - ./vendor/docker/docker-compose.env
      - ./vendor/docker/docker-compose-test.env
    depends_on:
      - db_migrate
      - memcached
      - postgres
      - redis
    profiles:
      - test
    volumes:
      - .:/app/samvera/hyrax-webapp
      - test-derivatives:/app/samvera/hyrax-webapp/derivatives
      - test-uploads:/app/samvera/hyrax-webapp/uploads
      - test-public:/app/samvera/hyrax-webapp/public
      - test-tmp:/app/samvera/hyrax-webapp/tmp
    networks:
      - morphosource

  db_migrate:
    build:
      context: .
      target: morphosource
      args:
        - EXTRA_APK_PACKAGES=git less
    container_name: db_migrate
    user: app
    env_file:
      - ./vendor/docker/credentials.env
      - ./vendor/docker/docker-compose.env
    command: sh -c 'bundle && db-migrate-seed.sh'
    depends_on:
      - postgres
      - fcrepo
      - solr
    volumes:
      - .:/app/samvera/hyrax-webapp
      - rails-public:/app/samvera/hyrax-webapp/public
      - rails-tmp:/app/samvera/hyrax-webapp/tmp
    networks:
      - morphosource

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./vendor/docker/credentials.env
      - ./vendor/docker/docker-compose.env
    # ports:
    #  - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - morphosource

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    container_name: fcrepo
    volumes:
      - fcrepo:/data
      - ./vendor/docker/fcrepo/fedora.xml:/var/lib/jetty/webapps/fedora.xml
    #ports: # Re-open ports for local dev environments
    #  - 8080:8080
    networks:
      - morphosource

  memcached:
    image: memcached
    container_name: memcached
    # ports:
    #  - '11211:11211'
    networks:
      - morphosource

  redis:
    image: redis:5-alpine
    container_name: redis
    volumes:
      - redis:/data
    networks:
      - morphosource

  solr:
    image: solr:7.7.3
    container_name: solr
    #ports: # Re-open ports for local dev environments
    #  - 8983:8983
    command:
      - sh
      - "-c"
      - "solr-precreate hydra-development /core_config"
    volumes:
      - solr_home:/opt/solr/server/solr/mycores
      - ./solr/config:/core_config/conf
    networks:
      - morphosource

  apache: # Currently non-functional on Apple Silicon Macs
    image: 'bitnami/apache:latest'
    container_name: apache
    user: root
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./vendor/docker/docker-compose.env
    profiles:
      - apache
    volumes:
    - ./vendor/docker/apache/vhost.conf:/vhosts/vhost.conf:ro
    # - ./vendor/docker/apache/certs:/certs
    networks:
      - morphosource

volumes:
  db:
  fcrepo:
  hyrax-derivatives:
  hyrax-uploads:
  rails-public:
  rails-tmp:
  redis:
  solr_home:
  test-derivatives:
  test-uploads:
  test-public:
  test-tmp:

networks:
  morphosource:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-morphosource
    name: morphosource
