# config/models/user_profile_types.yml
profile_types:
  universal:
    required_metadata_fields: email, first_name, last_name, country, state_or_province
    metadata_fields: middle_name, city, orcid, social_media_handles, website, typical_usage
  faculty: 
    label: "Faculty or Staff (University, Museum, and/or Library)"
    required_metadata_fields: academic_institution_or_school, department, academic_field
    metadata_fields: academic_subfield
  faculty_k12: 
    label: "Faculty or Staff (K-12)"
    required_metadata_fields: academic_institution_or_school, department, academic_field
    metadata_fields: academic_subfield
  educator_other:
    label: "Educator (Other)"
    required_metadata_fields: academic_institution_or_school, academic_field, mentor_or_advisor
    metadata_fields: department, academic_subfield
  student_postgrad:
    label: "Student (Post-Graduate)"
    required_metadata_fields: academic_institution_or_school, department, academic_field, mentor_or_advisor
    metadata_fields: academic_subfield
  student_undergrad: 
    label: "Student (Undergraduate)"
    required_metadata_fields: academic_institution_or_school, academic_field
    metadata_fields: department, instructor
  student_k12:
    label: "Student (K-12)"
    required_metadata_fields: academic_institution_or_school
    metadata_fields: instructor
  professional:
    label: "Private Industry or Government Professional"
    required_metadata_fields: organization
  artist:
    label: "artist"
    metadata_fields: organization
  individual:
    label: "Private Individual or Other"