# config/models/user_profile_types.yml
profile_types:
  universal:
    label: ""
    required_metadata_fields: [email, first_name, last_name, country, state]
    metadata_fields: [middle_name, city, orcid, social_media_handles, website, typical_usage]
  faculty: 
    label: "Faculty or Staff (University, Museum, and/or Library)"
    required_metadata_fields: [academic_institution_or_school, department, academic_field]
    metadata_fields: [academic_subfield]
    demographics: ["Faculty (Univ or Post-Secondary)", "Faculty (Post-Graduate)", "University Staff", "General Educator", "Museum Curator or Collections Manager", "Museum Staff", "Librarian", "IT Professional", "Researcher"]
  faculty_k12: 
    label: "Faculty or Staff (K-12)"
    required_metadata_fields: [academic_institution_or_school, department, academic_field]
    metadata_fields: [academic_subfield]
    demographics: ["Faculty (K-6)", "Faculty (7-12)", "General Educator", "Librarian", "IT Professional"]
  educator_other:
    label: "Educator (Other)"
    required_metadata_fields: [academic_institution_or_school, academic_field, mentor_or_advisor]
    metadata_fields: [department, academic_subfield]
    demographics: ["Faculty (K-6)", "Faculty (7-12)", "Faculty (University or Post-Secondary)", "Faculty (Post-Graduate)", "General Educator"] 
  student_postgrad:
    label: "Student (Post-Graduate)"
    required_metadata_fields: [academic_institution_or_school, department, academic_field, mentor_or_advisor]
    metadata_fields: [academic_subfield]
    demographics: ["Student (Post-Graduate)"]
  student_undergrad: 
    label: "Student (Undergraduate)"
    required_metadata_fields: [academic_institution_or_school, academic_field]
    metadata_fields: [department, instructor]
    demographics: ["Student (University or Post-Secondary)"]
  student_k12:
    label: "Student (K-12)"
    required_metadata_fields: [academic_institution_or_school]
    metadata_fields: [instructor]
    demographics: ["Student (Grades K-6)", "Student (Grades 7-12)"]
  professional:
    label: "Private Industry or Government Professional"
    required_metadata_fields: [affiliation]
    metadata_fields: []
    demographics: ["Private Industry Professional", "Government Employee", "IT Professional"]
  artist:
    label: "Artist"
    required_metadata_fields: []
    metadata_fields: [affiliation]
    demographics: ["Artist"]
  individual:
    label: "Private Individual or Other"
    required_metadata_fields: []
    metadata_fields: [] 
    demographics: ["Private Individual"]
