providers:
  # MCZ Special Collections
  000357979:
    publisher: Museum of Comparative Zoology, Harvard University
    rights_holder: President and Fellows of Harvard College (Copyright and License)
    data_manager_id: f95e50
    list_visibility: 'restricted'
    visibility: 'open'
    fileset_accessibility: 'restricted_download'
    download_permission: restricted_download
    download_reviewer: 2956
    preview_mode: Interactive/Embeddable
    copyright_statement: http://rightsstatements.org/vocab/InC/1.0/
    license: https://creativecommons.org/licenses/by-nc-nd/4.0/
    morphosource_use_agreement_type: Standard
    permits_3d_use: 3D Printing Limited
    required_archival_of_published_derivatives: On MorphoSource
    media_agreement_uri: https://mcz.harvard.edu/permissions-copyright

