# List of external document URLs for front page community menu
- label: hyrax.controls.links.community.community_hub
  url: https://github.com/MorphoSource/Community
  header: true
  footer: true
- label: hyrax.controls.links.community.announcements
  url: https://github.com/MorphoSource/Community/discussions/categories/announcements
  header: true
  footer: false
- label: hyrax.controls.links.community.roadmap
  url: https://github.com/orgs/MorphoSource/projects/2
  header: true
  footer: true
- label: hyrax.controls.links.community.discussions
  url: https://github.com/MorphoSource/Community/discussions/categories/general
  header: true
  footer: true
- label: hyrax.controls.links.community.questions_and_answers
  url: https://github.com/MorphoSource/Community/discussions/categories/q-a
  header: true
  footer: true