# List of external document URLs for front page docs menu
- label: hyrax.controls.links.docs.about
  url: /docs/about
  header: false
  footer: true
- label: hyrax.controls.links.docs.all_docs
  url: https://duke.atlassian.net/wiki/spaces/MD/overview?homepageId=35422252
  header: true
  footer: true
- label: hyrax.controls.links.docs.guide
  url: https://duke.atlassian.net/wiki/spaces/MD/pages/35422411/Standard+User+Docs
  header: true
  footer: false
- label: hyrax.controls.links.docs.contributors
  url: https://duke.atlassian.net/wiki/spaces/MD/pages/35422310/Contributor+User+Docs
  header: true
  footer: false
- label: hyrax.controls.links.docs.deposit_costs
  url: https://duke.atlassian.net/wiki/spaces/MD/pages/274268722/Data+Deposit+Costs
  header: true
  footer: false
- label: hyrax.controls.links.docs.citation
  url: https://duke.atlassian.net/wiki/spaces/MD/pages/35422721/Reference+and+Citation+of+Media+and+Projects
  header: true
  footer: false
- label: hyrax.controls.links.docs.faq
  url: https://duke.atlassian.net/wiki/spaces/MD/pages/35422899/Frequently+Asked+Questions
  header: true
  footer: false
- label: hyrax.controls.links.docs.deposit_structure
  url: https://duke.atlassian.net/wiki/spaces/MD/pages/35423429/Specimens+per+scan+Scans+per+media+deposit
  header: false
  footer: false