Hyrax.publisher.subscribe(Morphosource::Listeners::DeleteDeviceReservedArkListener.new)
Hyrax.publisher.subscribe(Morphosource::Listeners::DestroyProxyDepositRequestsListener.new)
Hyrax.publisher.subscribe(Morphosource::Listeners::IndexRelatedWorksListener.new)
Hyrax.publisher.subscribe(Morphosource::Listeners::MintDeviceArkListener.new)
Hyrax.publisher.subscribe(Morphosource::Listeners::UpdateDeviceArkStatusListener.new)
