# config/authorities/countries.yml
# Getty Thesaurus of Geographic Names Country List
# Derived from http://baskauf.blogspot.com/2016/04/controlled-values-for-country-from.html
# and specifically https://gist.github.com/baskaufs/799aace5cbc36a323919a569416e9c4a
terms:
- id: Afghanistan
  term: Afghanistan
  active: true
  continent: Asia
- id: Albania
  term: Albania
  active: true
  continent: Europe
- id: Algeria
  term: Algeria
  active: true
  continent: Africa
- id: Andorra
  term: Andorra
  active: true
  continent: Europe
- id: Angola
  term: Angola
  active: true
  continent: Africa
- id: Antigua and Barbuda
  term: Antigua and Barbuda
  active: true
  continent: North America
- id: Argentina
  term: Argentina
  active: true
  continent: South America
- id: Armenia
  term: Armenia
  active: true
  continent:
    - Asia
    - Europe
- id: Australia
  term: Australia
  active: true
  continent: Oceania
- id: Austria
  term: Austria
  active: true
  contient: Europe
  continent: Europe
- id: Azerbaijan
  term: Azerbaijan
  active: true
  continent:
    - Asia
    - Europe
- id: Bahamas
  term: Bahamas
  active: true
  continent: North America
- id: Bahrain
  term: Bahrain
  active: true
  continent: Asia
- id: Bangladesh
  term: Bangladesh
  active: true
  continent: Asia
- id: Barbados
  term: Barbados
  active: true
  continent: North America
- id: Belarus
  term: Belarus
  active: true
  continent: Europe
- id: Belgium
  term: Belgium
  active: true
  continent: Europe
- id: Belize
  term: Belize
  active: true
  continent: North America
- id: Benin
  term: Benin
  active: true
  continent: Africa
- id: Bhutan
  term: Bhutan
  active: true
  continent: Asia
- id: Bolivia
  term: Bolivia
  active: true
  continent: South America
- id: Bosnia and Herzegovina
  term: Bosnia and Herzegovina
  active: true
  continent: Europe
- id: Botswana
  term: Botswana
  active: true
  continent: Africa
- id: Brazil
  term: Brazil
  active: true
  continent: South America
- id: Brunei Darussalam
  term: Brunei Darussalam
  active: true
  continent: Asia
- id: Bulgaria
  term: Bulgaria
  active: true
  continent: Europe
- id: Burkina Faso
  term: Burkina Faso
  active: true
  continent: Africa
- id: Burundi
  term: Burundi
  active: true
  continent: Africa
- id: Cambodia
  term: Cambodia
  active: true
  continent: Asia
- id: Cameroon
  term: Cameroon
  active: true
  continent: Africa
- id: Canada
  term: Canada
  active: true
  continent: North America
- id: Cape Verde
  term: Cape Verde
  active: true
  continent: Africa
- id: Central African Republic
  term: Central African Republic
  active: true
  continent: Africa
- id: Chad
  term: Chad
  active: true
  continent: Africa
- id: Chile
  term: Chile
  active: true
  continent: South America
- id: China
  term: China
  active: true
  continent: Asia
- id: Colombia
  term: Colombia
  active: true
  continent: South America
- id: Comoros
  term: Comoros
  active: true
  continent: Africa
- id: Congo (Republic of)
  term: Congo (Republic of)
  active: true
  continent: Africa
- id: Congo (Democratic Republic of)
  term: Congo (Democratic Republic of)
  active: true
  continent: Africa
- id: Costa Rica
  term: Costa Rica
  active: true
  continent: North America
- id: Côte d'Ivoire
  term: Côte d'Ivoire
  active: true
  continent: Africa
- id: Croatia
  term: Croatia
  active: true
  continent: Europe
- id: Cuba
  term: Cuba
  active: true
  continent: North America
- id: Cyprus
  term: Cyprus
  active: true
  continent:
    - Asia
    - Europe
- id: Czech Republic
  term: Czech Republic
  active: true
  continent: Europe
- id: Denmark
  term: Denmark
  active: true
  continent: Europe
- id: Djibouti
  term: Djibouti
  active: true
  continent: Africa
- id: Dominica
  term: Dominica
  active: true
  continent: North America
- id: Dominican Republic
  term: Dominican Republic
  active: true
  continent: North America
- id: Ecuador
  term: Ecuador
  active: true
  continent: South America
- id: Egypt
  term: Egypt
  active: true
  continent: Africa
- id: El Salvador
  term: El Salvador
  active: true
  continent: North America
- id: Equatorial Guinea
  term: Equatorial Guinea
  active: true
  continent: Africa
- id: Eritrea
  term: Eritrea
  active: true
  continent: Africa
- id: Estonia
  term: Estonia
  active: true
  continent: Europe
- id: Ethiopia
  term: Ethiopia
  active: true
  continent: Africa
- id: Federated States of Micronesia
  term: Federated States of Micronesia
  active: true
  continent: Oceania
- id: Fiji
  term: Fiji
  active: true
  continent: Oceania
- id: Finland
  term: Finland
  active: true
  continent: Europe
- id: France
  term: France
  active: true
  continent: Europe
- id: Gabon
  term: Gabon
  active: true
  continent: Africa
- id: Georgia
  term: Georgia
  active: true
  continent:
    - Asia
    - Europe
- id: Germany
  term: Germany
  active: true
  continent: Europe
- id: Ghana
  term: Ghana
  active: true
  continent: Africa
- id: Greece
  term: Greece
  active: true
  continent: Europe
- id: Greenland
  term: Greenland
  active: true
  continent: North America
- id: Grenada
  term: Grenada
  active: true
  continent: North America
- id: Guatemala
  term: Guatemala
  active: true
  continent: North America
- id: Guinea
  term: Guinea
  active: true
  continent: Oceania
- id: Guinea-Bissau
  term: Guinea-Bissau
  active: true
  continent: Africa
- id: Guyana
  term: Guyana
  active: true
  continent: South America
- id: Haiti
  term: Haiti
  active: true
  continent: North America
- id: Holy See
  term: Holy See
  active: true
  continent: Europe
- id: Honduras
  term: Honduras
  active: true
  continent: North America
- id: Hungary
  term: Hungary
  active: true
  continent: Europe
- id: Iceland
  term: Iceland
  active: true
  continent: Europe
- id: India
  term: India
  active: true
  continent: Asia
- id: Indonesia
  term: Indonesia
  active: true
  continent: Asia
- id: Iran
  term: Iran
  active: true
  continent: Asia
- id: Iraq
  term: Iraq
  active: true
  continent: Asia
- id: Ireland
  term: Ireland
  active: true
  continent: Europe
- id: Israel
  term: Israel
  active: true
  continent: Asia
- id: Italy
  term: Italy
  active: true
  continent: Europe
- id: Jamaica
  term: Jamaica
  active: true
  continent: North America
- id: Japan
  term: Japan
  active: true
  continent: Asia
- id: Jordan
  term: Jordan
  active: true
  continent: Asia
- id: Kazakhstan
  term: Kazakhstan
  active: true
  continent:
    - Asia
    - Europe
- id: Kenya
  term: Kenya
  active: true
  continent: Africa
- id: Kiribati
  term: Kiribati
  active: true
  continent: Oceania
- id: Kuwait
  term: Kuwait
  active: true
  continent: Asia
- id: Kyrgyzstan
  term: Kyrgyzstan
  active: true
  continent: Asia
- id: Laos
  term: Laos
  active: true
  continent: Asia
- id: Latvia
  term: Latvia
  active: true
  continent: Europe
- id: Lebanon
  term: Lebanon
  active: true
  continent: Asia
- id: Lesotho
  term: Lesotho
  active: true
  continent: Africa
- id: Liberia
  term: Liberia
  active: true
  continent: Africa
- id: Libya
  term: Libya
  active: true
  continent: Africa
- id: Liechtenstein
  term: Liechtenstein
  active: true
  continent: Europe
- id: Lithuania
  term: Lithuania
  active: true
  continent: Europe
- id: Luxembourg
  term: Luxembourg
  active: true
  continent: Europe
- id: Madagascar
  term: Madagascar
  active: true
  continent: Africa
- id: Malawi
  term: Malawi
  active: true
  continent: Africa
- id: Malaysia
  term: Malaysia
  active: true
  continent: Asia
- id: Maldives
  term: Maldives
  active: true
  continent: Asia
- id: Mali
  term: Mali
  active: true
  continent: Africa
- id: Malta
  term: Malta
  active: true
  continent: Europe
- id: Marshall Islands
  term: Marshall Islands
  active: true
  continent: Oceania
- id: Mauritania
  term: Mauritania
  active: true
  continent: Africa
- id: Mauritius
  term: Mauritius
  active: true
  continent: Africa
- id: Mexico
  term: Mexico
  active: true
  continent: North America
- id: Moldova
  term: Moldova
  active: true
  continent: Europe
- id: Monaco
  term: Monaco
  active: true
  continent: Europe
- id: Mongolia
  term: Mongolia
  active: true
  continent: Asia
- id: Montenegro
  term: Montenegro
  active: true
  continent: Europe
- id: Montserrat
  term: Montserrat
  active: true
  continent: North America
- id: Morocco
  term: Morocco
  active: true
  continent: Africa
- id: Mozambique
  term: Mozambique
  active: true
  continent: Africa
- id: Myanmar
  term: Myanmar
  active: true
  continent: Asia
- id: Namibia
  term: Namibia
  active: true
  continent: Africa
- id: Nauru
  term: Nauru
  active: true
  continent: Oceania
- id: Nepal
  term: Nepal
  active: true
  continent: Asia
- id: Netherlands
  term: Netherlands
  active: true
  continent: Europe
- id: New Zealand
  term: New Zealand
  active: true
  continent: Oceania
- id: Nicaragua
  term: Nicaragua
  active: true
  continent: North America
- id: Niger
  term: Niger
  active: true
  continent: Africa
- id: Nigeria
  term: Nigeria
  active: true
  continent: Africa
- id: North Korea
  term: North Korea
  active: true
  continent: Asia
- id: Norway
  term: Norway
  active: true
  continent: Europe
- id: Oman
  term: Oman
  active: true
  continent: Asia
- id: Pakistan
  term: Pakistan
  active: true
  continent: Asia
- id: Palau
  term: Palau
  active: true
  continent: Oceania
- id: Palestine
  term: Palestine
  active: true
  continent: Asia
- id: Panama
  term: Panama
  active: true
  continent: North America
- id: Papua New Guinea
  term: Papua New Guinea
  active: true
  continent: Oceania
- id: Paraguay
  term: Paraguay
  active: true
  continent: South America
- id: Peru
  term: Peru
  active: true
  continent: South America
- id: Philippines
  term: Philippines
  active: true
  continent: Asia
- id: Poland
  term: Poland
  active: true
  continent: Europe
- id: Portugal
  term: Portugal
  active: true
  continent: Europe
- id: Puerto Rico
  term: Puerto Rico
  active: true
  continent: North America
- id: Qatar
  term: Qatar
  active: true
  continent: Asia
- id: Romania
  term: Romania
  active: true
  continent: Europe
- id: Russia
  term: Russia
  active: true
  continent:
    - Asia
    - Europe
- id: Rwanda
  term: Rwanda
  active: true
  continent: Africa
- id: Saint Kitts and Nevis
  term: Saint Kitts and Nevis
  active: true
  continent: North America
- id: Saint Lucia
  term: Saint Lucia
  active: true
  continent: North America
- id: Saint Vincent and the Grenadines
  term: Saint Vincent and the Grenadines
  active: true
  continent: North America
- id: Samoa
  term: Samoa
  active: true
  continent: Oceania
- id: San Marino
  term: San Marino
  active: true
  continent: Europe
- id: Sao Tome and Principe
  term: Sao Tome and Principe
  active: true
  continent: Africa
- id: Saudi Arabia
  term: Saudi Arabia
  active: true
  continent: Asia
- id: Scotland
  term: Scotland
  active: true
  continent: Europe
- id: Senegal
  term: Senegal
  active: true
  continent: Africa
- id: Serbia
  term: Serbia
  active: true
  continent: Europe
- id: Seychelles
  term: Seychelles
  active: true
  continent: Africa
- id: Sierra Leone
  term: Sierra Leone
  active: true
  continent: Africa
- id: Singapore
  term: Singapore
  active: true
  continent: Asia
- id: Slovakia
  term: Slovakia
  active: true
  continent: Europe
- id: Slovenia
  term: Slovenia
  active: true
  continent: Europe
- id: Solomon Islands
  term: Solomon Islands
  active: true
  continent: Oceania
- id: Somalia
  term: Somalia
  active: true
  continent: Africa
- id: South Africa
  term: South Africa
  active: true
  continent: Africa
- id: South Korea
  term: South Korea
  active: true
  continent: Asia
- id: South Sudan
  term: South Sudan
  active: true
  continent: Africa
- id: Spain
  term: Spain
  active: true
  continent: Europe
- id: Sri Lanka
  term: Sri Lanka
  active: true
  continent: Asia
- id: Sudan
  term: Sudan
  active: true
  continent: Africa
- id: Suriname
  term: Suriname
  active: true
  continent: South America
- id: Swaziland
  term: Swaziland
  active: true
  continent: Africa
- id: Sweden
  term: Sweden
  active: true
  continent: Europe
- id: Switzerland
  term: Switzerland
  active: true
  continent: Europe
- id: Syria
  term: Syria
  active: true
  continent: Asia
- id: Taiwan
  term: Taiwan
  active: true
  continent: Asia
- id: Tajikistan
  term: Tajikistan
  active: true
  continent: Asia
- id: Tanzania
  term: Tanzania
  active: true
  continent: Africa
- id: Thailand
  term: Thailand
  active: true
  continent: Asia
- id: Timor-Leste
  term: Timor-Leste
  active: true
  continent: Asia
- id: Togo
  term: Togo
  active: true
  continent: Africa
- id: Tonga
  term: Tonga
  active: true
  continent: Oceania
- id: Trinidad and Tobago
  term: Trinidad and Tobago
  active: true
  continent: North America
- id: Tunisia
  term: Tunisia
  active: true
  continent: Africa
- id: Turkey
  term: Turkey
  active: true
  continent:
    - Asia
    - Europe
- id: Tuvalu
  term: Tuvalu
  active: true
  continent: Oceania
- id: Uganda
  term: Uganda
  active: true
  continent: Africa
- id: Ukraine
  term: Ukraine
  active: true
  continent: Europe
- id: United Arab Emirates
  term: United Arab Emirates
  active: true
  continent: Asia
- id: United Kingdom
  term: United Kingdom
  active: true
  continent: Europe
- id: United States
  term: United States
  active: true
  continent: North America
- id: Uruguay
  term: Uruguay
  active: true
  continent: South America
- id: Uzbekistan
  term: Uzbekistan
  active: true
  continent: Asia
- id: Vanuatu
  term: Vanuatu
  active: true
  continent: Oceania
- id: Venezuela
  term: Venezuela
  active: true
  continent: South America
- id: Vietnam
  term: Vietnam
  active: true
  continent: Asia
- id: Yemen
  term: Yemen
  active: true
  continent: Asia
- id: Zambia
  term: Zambia
  active: true
  continent: Africa
- id: Zimbabwe
  term: Zimbabwe
  active: true
  continent: Africa