terms:
  - id: Direct (X-Ray photoconductor)
    term: Direct (X-Ray photoconductor)
  - id: Scintillator (Phosphor used)
    term: Scintillator (Phosphor used)
  - id: Storage (Storage Phosphor)
    term: Storage (Storage Phosphor)
  - id: Film (Scanned film/screen)
    term: Film (Scanned film/screen)
