# config/authorities/modalities.yml
# URI for terms list: https://www.idigbio.org/wiki/index.php/3D_Scan_Modality_Subtypes
terms:
  - id: MicroNanoXRayComputedTomography
    term: X-Ray Computed Tomography (CT/microCT)
    active: true
  - id: MagneticResonanceImaging
    term: Magnetic Resonance Imaging (MRI)
    active: true
  - id: PositronEmissionTomography
    term: Positron Emission Tomography (PET)
    active: true
  - id: SinglePhotonEmissionComputedTomography
    term: Single Photon Emission Computed Tomography (SPECT)
    active: true
  - id: NeutronComputedTomography
    term: Neutron Computed Tomography (NCT)
    active: true
  - id: SynchrotronImaging
    term: Synchrotron Imaging
    active: true
  - id: Photogrammetry
    term: Photogrammetry
    active: true
  - id: SequentialSectionScan
    term: Sequential Section Scan
    active: true
  - id: StructuredLight
    term: Structured Light
    active: true
  - id: LaserScan
    term: Laser Scan
    active: true
  - id: ConfocalImageStacking
    term: Confocal Image Stacking
    active: true
  - id: Infrared
    term: Infrared
    active: true
  - id: ReflectanceTransformationImaging
    term: Reflectance Transformation Imaging
    active: true
  - id: Photography
    term: Photography
    active: true
  - id: ScanningElectronMicroscopy
    term: Scanning Electron Microscopy
    active: true
  - id: BornDigital
    term: Born Digital
    active: true
  - id: XRay
    term: X-Ray
    active: true
  - id: LaserAidedProfiling
    term: Laser Aided Profiling
    active: true
  - id: Video
    term: Video
    active: true
