terms:
  - id: Museum, Department, or Lab Collection
    term: Museum, Department, or Lab Collection
  - id: Scanning Facility
    term: Scanning Facility
  - id: Collection and Scanning Facility
    term: Collection and Scanning Facility
