terms:
  - id: Female
    term: Female
  - id: Male
    term: Male
  - id: Unknowable
    term: Unknowable
  - id: Undetermined
    term: Undetermined
  - id: Hermaphrodite
    term: Hermaphrodite
  - id: Gynandromorph
    term: Gynandromorph
