module Morphosource
  module Characterization
    module Valkyrie
      class CharacterizationService < Hyrax::Characterization::ValkyrieCharacterizationService
        ##
        # @api public
        # @param [Hyrax::FileMetadata] metadata  which has properties to recieve characterization values
        # @param [Valkyrie::StorageAdapter::StreamFile] source to run characterization against
        # @param [boolean] publish_characterized whether to publish event signaling characterize is done
        # @param [Hash] options the options pass to characterization
        # @option options [Hash{Symbol => Symbol}] parser_mapping
        # @option options [Hydra::Works::Characterization::FitsDocument] parser
        # @option options [Symbol] ch12n_tool
        #
        # @return [void]
        def self.run(metadata:, file:, user: ::User.system_user, publish_characterized: true, **options)
          new(metadata: metadata, file: file, **options).characterize
          saved = Hyrax.persister.save(resource: metadata)
          Hyrax.publisher.publish('file.metadata.updated', metadata: saved, user: user)

          if publish_characterized
            Hyrax.publisher.publish('file.characterized',
                                    file_set: Hyrax.query_service.find_by(id: saved.file_set_id),
                                    file_id: saved.id.to_s,
                                    path_hint: saved.file_identifier.to_s)
          end

          return saved
        end

        ##
        # @!attribute [rw] source
        #   @return [Valkyrie::StorageAdapter::StreamFile]
        # @!attribute [rw] metadata
        #   @return [Hyrax::FileMetadata]
        # @!attribute [rw] parser
        #   @return [Hydra::Works::Characterization::FitsDocument]
        # @!attribute [rw] source
        #   @return [Valkyrie::StorageAdapter::StreamFile]
        # @!attribute [rw] tools
        #   can be :fits, :fits_servlet, :ffprobe or any other service added to HydraFileCharacterization
        #   note that ffprope is faster but only works on AV files.
        #   MorphoSource also supports use of :blender tool for 3D content.
        #   @return [Symbol]
        # @!attribute [rw] characterizer_config
        #   Hash with tool key and tool-specific configuration for things like tool paths
        attr_accessor :mapping, :metadata, :parser, :source, :tools, :characterizer_config

        # Property values where we want to use the last value generated by a tool in tool sequence
        PROPERTY_VALUES_REPLACE_PREVIOUS = [
          :point_count, :face_count, :bounding_box_x, :bounding_box_y, :bounding_box_z,
          :has_uv_space, :vertex_color, :centroid_x, :centroid_y, :centroid_z, :centroid_method
        ]

        ##
        # @api private
        def initialize( # rubocop:disable Metrics/ParameterLists
          metadata:,
          file:,
          characterizer: Hydra::FileCharacterization,
          parser_mapping: Hydra::Works::Characterization.mapper,
          parser: Hydra::Works::Characterization::FitsDocument.new,
          ch12n_tool: :fits,
          characterizer_config: {
            fits: Hydra::Derivatives.fits_path,
            blender: Hyrax.config.blender_path
          }
        )
          @characterizer       = characterizer
          @metadata            = metadata
          @source              = file
          @mapping             = parser_mapping
          @parser              = parser
          @tools               = ch12n_tool
          @characterizer_config = characterizer_config
        end

        def characterize
          terms = parse_metadata(extract_metadata(content))
          apply_metadata(terms)
        end

        protected

        # todovalk: implement support for remote URLs?
        def content
          if source.is_a? File
            source
          elsif source_file_path.present? && File.exist?(source_file_path)
            File.open(source_file_path)
          else
            source.rewind
            source.read
          end
        end

        # Different ways to get local file path from source object or string
        def source_file_path
          @source_file_path ||= begin
            if source.respond_to?(:disk_path)
              source.disk_path
            elsif source.respond_to?(:io) && source.io.respond_to?(:path)
              source.io.path
            elsif source.is_a?(String)
              source
            else
              nil
            end
          end
        end

        def extract_metadata(content)
          @characterizer.characterize(content, file_name, tools) do |cfg|
            characterizer_config.each do |key, value|
              cfg[key] = value
            end
          end
        end

        def append_property_value(property, value)
          if property == :mime_type
            # mime type special case: overwrites previous value as string
            value = value
          elsif property == :height || property == :width
            # height and width special case: get max of multiple values as string
            value = (metadata.public_send(property) + Array(value)).map(&:to_i).max.to_s
          elsif PROPERTY_VALUES_REPLACE_PREVIOUS.include? property
            # overwrite special case: overwrite previous value as array
            value = Array(value)
          else
            # standard case: append new value to previous values as array
            value = metadata.public_send(property) + Array(value)
          end

          metadata.public_send("#{property}=", value)
        end
      end
    end
  end
end