development:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: 6379
  password: <%= ENV['REDIS_PASSWORD'] %>
test:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: 6379
production:
  url: <%= ENV['REDIS_URL'] || "redis://:#{REDIS_PASSWORD}@#{REDIS_HOST}:6379/" %>
