# config/submission.yml
# Raw or derived status and examples for media and modality combinations
status:
  Image:
    MicroNanoXRayComputedTomography: derived
    MagneticResonanceImaging: derived
    SynchrotronImaging: derived
    Photogrammetry: derived
    StructuredLight: derived
    LaserScan: derived
    BornDigital: derived
    Video: derived
    Photography: any
    XRay: any
    SlideScan: any
  Video:
    MicroNanoXRayComputedTomography: derived
    MagneticResonanceImaging: derived
    SynchrotronImaging: derived
    Photogrammetry: derived
    StructuredLight: derived
    LaserScan: derived
    BornDigital: derived
    XRay: derived
    Photography: derived
    Video: any
    SlideScan: derived
  CTImageSeries:
    MicroNanoXRayComputedTomography: any
    MagneticResonanceImaging: any
    SynchrotronImaging: any
    Photogrammetry: none
    StructuredLight: none
    LaserScan: none
    Photography: none
    Video: none
    SlideScan: none
  PhotogrammetryImageSeries:
    MicroNanoXRayComputedTomography: none
    MagneticResonanceImaging: none
    SynchrotronImaging: none
    Photogrammetry: any
    StructuredLight: none
    LaserScan: none
    Photography: none
    Video: none
    SlideScan: none
  Mesh:
    MicroNanoXRayComputedTomography: derived
    MagneticResonanceImaging: derived
    SynchrotronImaging: derived
    Photogrammetry: derived
    Video: derived
    StructuredLight: any
    LaserScan: any
    BornDigital: any
    Photography: none
    SlideScan: derived
  SlideImageSeries:
    MicroNanoXRayComputedTomography: none
    MagneticResonanceImaging: none
    SynchrotronImaging: none
    Photogrammetry: none
    StructuredLight: none
    LaserScan: none
    Photography: none
    Video: none
    SlideScan: any
examples:
  Image:
    Photography:
      raw:
        - Image produced by camera with no filters or processing applied
      derived:
        - Image with filter or processing applied (dimension reduction, contrast enhancement, etc.)
    SlideScan:
      raw:
        - Slide image with no filters or processing applied
      derived:
        - Slide image with filter or processing applied (dimension reduction, contrast enhancement, etc.)
  Video:
    Video:
      raw:
        - Initial video with no filters or processing applied
      derived:
        - Video with filter or processing applied
  CTImageSeries:
    MicroNanoXRayComputedTomography:
      raw:
        - X-ray projection images produced by scanner software
      derived:
        - Reconstructed image slices
        - X-ray projection images with subsequent processing
    MagneticResonanceImaging:
      raw:
        - X-ray projection images produced by scanner software
      derived:
        - Reconstructed image slices
        - X-ray projection images with subsequent processing
    SynchrotronImaging:
      raw:
        - X-ray projection images produced by scanner software
      derived:
        - Reconstructed image slices
        - X-ray projection images with subsequent processing
  PhotogrammetryImageSeries:
    Photogrammetry:
      raw:
        - Initial images produced by camera with no filters or processing applied
      derived:
        - Camera images with any type of processing (masking, etc.)
  Mesh:
    StructuredLight:
      raw:
        - Data produced by scanner software with no additional processing applied
      derived:
        - Mesh or point cloud with subsequent processing (merging, denoising, simplification, etc.)
    LaserScan:
      raw:
        - Data produced by scanner software with no additional processing applied
      derived:
        - Mesh or point cloud with subsequent processing (merging, denoising, simplification, etc.)
  SlideImageSeries:
    SlideScan:
      raw:
        - Images with no filters or processing applied
      derived:
        - Images with any type of processing (masking, etc.)
