# frozen_string_literal: true

require 'rails_helper'

RSpec.describe ImagingEventResourceForm do
  subject { described_class }

  it "includes expected form behaviors" do
    expect(subject.included_modules).to include(
      Morphosource::ValkyrieFormBehavior,
      Morphosource::FormMethods
    )
  end

  describe 'title validation' do
    it 'does not require a title (auto-generated by set_title transaction step)' do
      validators = described_class.validators_on(:title)
      presence_validators = validators.select { |v| v.is_a?(ActiveModel::Validations::PresenceValidator) }
      title_required = presence_validators.any? { |v| v.attributes.include?(:title) }
      expect(title_required).to be false
    end
  end

  describe '#universal_terms' do
    let(:form) { described_class.new(ImagingEventResource.new) }

    it 'returns the fields shown for all modalities' do
      expect(form.universal_terms).to eq([:ie_modality, :description, :creator, :software, :date_created])
    end
  end

  describe '#modality_specific_terms' do
    let(:form) { described_class.new(ImagingEventResource.new) }

    it 'returns the modality-specific fields' do
      expect(form.modality_specific_terms).to include(
        :exposure_time, :voltage, :power, :amperage,
        :focal_length_type, :background_removal,
        :lens_make, :lens_model, :light_source,
        :slide_type
      )
    end

    it 'does not include universal fields' do
      expect(form.modality_specific_terms).not_to include(:ie_modality, :description, :creator, :software, :date_created)
    end
  end

  describe '#primary_terms' do
    let(:form) { described_class.new(ImagingEventResource.new) }

    it 'is the concatenation of universal_terms and modality_specific_terms' do
      expect(form.primary_terms).to eq(form.universal_terms + form.modality_specific_terms)
    end

    it 'does not include device_id or physical_object_id (injected by controller)' do
      expect(form.primary_terms).not_to include(:device_id, :physical_object_id)
    end
  end

  describe '.build_permitted_params' do
    it 'includes device_id and physical_object_id' do
      expect(described_class.build_permitted_params).to include(:device_id, :physical_object_id)
    end

    it 'includes basic submission fields' do
      expect(described_class.build_permitted_params).to include(
        :on_behalf_of, :visibility, :agreement_accepted, :admin_set_id
      )
    end
  end
end
