# frozen_string_literal: true

# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  self.indexer = Hyrax::CollectionWithBasicMetadataIndexer

  attr_accessor :organization_id

  before_create :add_date_uploaded

  after_destroy :destroy_default_groups, if: :type_assigns_groups?

  # editors group grants members ability to edit works in the collection, but not to edit collection metadata or grant permissions
  DEFAULT_GROUP_ROLES = %w[managers editors depositors downloaders viewers].freeze

  # override Hyrax::CollectionBehavior to add editors and downloaders to read_groups
  def permission_template_read_groups
    (permission_template.agent_ids_for(access: 'view', agent_type: 'group') + permission_template.agent_ids_for(access: 'edit_works', agent_type: 'group') +
    permission_template.agent_ids_for(access: 'download', agent_type: 'group') +
    permission_template.agent_ids_for(access: 'deposit', agent_type: 'group')).uniq -
    [::Ability.registered_group_name, ::Ability.public_group_name]
  end

  def human_readable_type
    if team?
      "Team"
    elsif project?
      "Project"
    else
      super
    end
  end

  def type_assigns_groups?
    team? || project?
  end

  # managers_group, depositors_group, editors_group, downloaders_group, and viewers_group methods
  DEFAULT_GROUP_ROLES.each do |role|
    define_method("#{role}_group") do
      Role.find_by(name: id.concat("_#{role}"))
    end
  end

  # managers, depositors, editors, downloaders, and viewers methods
  DEFAULT_GROUP_ROLES.each do |role|
    define_method(role) do
      Role.find_by(name: id.concat("_#{role}")).users
    end
  end

  def team?
    collection_type.title == 'Team'
  end

  def project?
    collection_type.title == 'Project'
  end

  def user_groups
    [managers_group, editors_group, depositors_group, downloaders_group, viewers_group]
  end

  def user_groups_names
    user_groups.map(&:name)
  end

  def group_members
    managers + editors + depositors + downloaders + viewers
  end

  def group_member_count
    group_members.count
  end

  def add_users_to_group(group, user_ids)
    user_ids.each do |u_id|
      u = User.find_by_user_key(u_id)
      group.users << u unless group_members.include? u
    end
  end

  def first_parent
    id = member_of_collection_ids.first
    id ? Collection.find(id) : nil
  end

  def parent_id
    member_of_collection_ids.first
  end

  def parent?
    !member_of_collections.empty?
  end

  def organization
    if parent_id
      Organization.where(team_id: parent_id).first
    else
      Organization.where(team_id: id).first
    end
  end

  def organization_name
    return nil if organization.nil?
    organization.title
  end

  # Create manager/depositor/viewer roles for each Team/Project collection
  def create_collection_groups
    DEFAULT_GROUP_ROLES.each do |role|
      Role.create(name: id.concat("_#{role}"))
    end
    add_depositor_to_managers
  end

  def copy_parent_membership(parent_id)
    parent = Collection.find(parent_id)
    DEFAULT_GROUP_ROLES.each do |role|
      parent.send(role).each do |member|
        send(role) << member unless group_members.include? member
      end
    end
    user_groups.each(&:save)
  end

  def remove_parent_membership(parent, user=nil)
    # do not remove the selected user from the collection members
    members = parent.group_members - [user]
    DEFAULT_GROUP_ROLES.each do |role|
      members.each do |member|
        send(role).delete(member)
      end
    end
  end

  # override the method from models/concerns/hyrax/collection_behavior.rb to apply collection permissions to works
  def add_member_objects(new_member_ids)
    Array(new_member_ids).collect do |member_id|
      member = ActiveFedora::Base.find(member_id)
      message = Hyrax::MultipleMembershipChecker.new(item: member).check(collection_ids: id, include_current_members: true)
      if message
        member.errors.add(:collections, message)
      else
        member.member_of_collections << self
        Hyrax::PermissionTemplateApplicator.apply(permission_template).to(model: member)
        member.save!
        InheritPermissionsJob.perform_later(member)
      end
      member
    end
  end

  def remove_member_objects(member_ids)
    member_ids.each do |id|
      work = ActiveFedora::Base.find(id)
      work.member_of_collections.delete self
      remove_team_access_grants(work)
      work.save!
      InheritPermissionsJob.perform_later(work)
    end
  end

  def remove_team_access_grants(work)
    work.edit_groups -= [managers_group.name, editors_group.name]
    work.read_groups -= [viewers_group.name]
    work.download_groups -= [downloaders_group.name]
  end

  def membership_of(user)
    membership_list = []
    membership_list << 'Manager' if managers.include?(user)
    membership_list << 'Editor' if editors.include?(user)
    membership_list << 'Depositor' if depositors.include?(user)
    membership_list << 'Viewer' if viewers.include?(user)
    membership_list << 'Downloader' if downloaders.include?(user)
    membership_list
  end

  def child_projects
    ActiveFedora::Base.where("member_of_collection_ids_ssim:#{id}").select{ |c| c.class == Collection && c.project? }
  end

  # override Hyrax::CollectionBehavior method to allow collection types to be changed
  def collection_type_gid=(new_collection_type_gid)
    new_collection_type = Hyrax::CollectionType.find_by_gid!(new_collection_type_gid)
    super
    @collection_type = new_collection_type
    collection_type_gid
  end

  def media_docs
    Morphosource::SolrService.new.get_docs("member_of_collection_ids_ssim:#{id} AND has_model_ssim:Media")
  end

  def media
    Media.where("member_of_collection_ids_ssim:#{id}")
  end

  private

    def add_depositor_to_managers
      user = User.find_by(ms_id: depositor)
      managers_group.users << user
      managers_group.save
    end

    def destroy_default_groups
      user_groups.compact.each(&:destroy)
    end

    def add_date_uploaded
      self.date_uploaded = date_uploaded.nil? ? Time.now : date_uploaded
    end
end
