# frozen_string_literal: true

# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  include ::Morphosource::CollectionBehavior
  include ::Morphosource::ProjectBehavior # project-specific behavior
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  self.indexer = Hyrax::CollectionWithBasicMetadataIndexer

  attr_accessor :organization_id

  before_create :add_date_uploaded

  after_destroy :reindex_collection_members
  after_destroy :destroy_default_groups, if: :type_assigns_groups?

  MANAGE_GROUP_ROLES = %w[managers].freeze
  # editors group grants members ability to edit works in the collection, but not to edit collection metadata or grant permissions
  EDIT_GROUP_ROLES = %w[managers editors].freeze
  # includes all groups that have edit access to the collection works plus downloaders
  DOWNLOAD_GROUP_ROLES = %w[managers editors downloaders].freeze
  # all groups except depositors grant ability to read works in the collection
  READ_GROUP_ROLES = %w[managers editors downloaders viewers].freeze
  # all groups
  # depositors can add works to the collection, but do not have additional access to other works in the collection
  DEFAULT_GROUP_ROLES = %w[managers editors depositors downloaders viewers].freeze

  def presenter_class
    team? ? Morphosource::Collections::TeamPresenter : Morphosource::Collections::ProjectPresenter
  end

  def human_readable_type
    collection_type.title
  end

  # UPGRADE5 Note: This method is defunct in Hyrax 5, yet we need it on this model, so putting it back in
  # But using new-style logic for getting collection type, which gets used elsewhere in 5
  # Maybe consider alternative approaches in the future
  def collection_type
    @collection_type ||= Hyrax::CollectionType.for(collection: self)
  end

  def type_assigns_groups?
    team? || project?
  end

  def media_inherit_permissions?
    team? || project?
  end

  # managers_group, depositors_group, editors_group, downloaders_group, and viewers_group methods
  DEFAULT_GROUP_ROLES.each do |role|
    define_method("#{role}_group") do
      Role.find_by(name: id&.concat("_#{role}"))
    end
  end

  # managers, depositors, editors, downloaders, and viewers methods
  DEFAULT_GROUP_ROLES.each do |role|
    define_method(role) do
      Role.find_by(name: id&.concat("_#{role}"))&.users || []
    end
  end

  def team?
    collection_type.title == 'Team'
  end

  def project?
    collection_type.title == 'Project'
  end

  def list?
    false
  end

  def media_list?
    false
  end

  def sequential_section_list?
    false
  end

  def organization_collection?
    false
  end

  # TODO: Alias this to organization_collection when migration
  # from works to collections is complete.
  # NB: Be very careful doing this as this method is used to differentiate work vs coll elsewhere
  def organization?
    false
  end

  def manages_objects_and_devices?
    false
  end

  def user_groups
    [managers_group, editors_group, depositors_group, downloaders_group, viewers_group]
  end

  def user_groups_names
    user_groups.map(&:name)
  end

  def group_members
    managers + editors + depositors + downloaders + viewers
  end

  def group_member_count
    group_members.count
  end

  def add_users_to_group(group, user_ids)
    user_ids.each do |u_id|
      u = User.find_by_user_key(u_id)
      group.users << u unless group_members.include? u
    end
  end

  def first_parent
    id = member_of_collection_ids.first
    id ? Collection.find(id) : nil
  end

  def parent_id
    member_of_collection_ids.first
  end

  def parent?
    !member_of_collections.empty?
  end

  def child_projects
    ActiveFedora::Base.where("member_of_collection_ids_ssim:#{id}")
  end

  def organization
    if parent_id
      Organization.where(team_id: parent_id)&.first
    else
      Organization.where(team_id: id)&.first
    end
  end

  def organization_name
    return nil if organization.nil?
    organization.title
  end

  # Create manager/depositor/viewer roles for each Team/Project collection
  def create_collection_groups
    self.class::DEFAULT_GROUP_ROLES.each do |role|
      name = id.concat("_#{role}")
      Role.create(name: name) unless Role.find_by(name: name)
    end
    add_depositor_to_managers
  end

  def copy_parent_membership(parent_id)
    parent = Collection.find(parent_id)
    DEFAULT_GROUP_ROLES.each do |role|
      parent.send(role).each do |member|
        send(role) << member unless group_members.include? member
      end
    end
    user_groups.each(&:save)
  end

  def remove_parent_membership(parent, user=nil)
    # do not remove the selected user from the collection members
    members = parent.group_members - [user]
    DEFAULT_GROUP_ROLES.each do |role|
      members.each do |member|
        send(role).delete(member)
      end
    end
  end

  # override the method from models/concerns/hyrax/collection_behavior.rb to apply collection permissions to works added to teams or projects
  def add_member_objects(new_members)
    members = Array(new_members)
    if members.first.is_a? String
      members = members.map { |m| ActiveFedora::Base.find(m) }
    end
    members.collect do |member|
      message = Hyrax::MultipleMembershipChecker.new(item: member).check(collection_ids: id, include_current_members: true)
      object_id = member.physical_object_id&.first
      if message
        member.errors.add(:collections, message)
      else
        member.member_of_collections << self
        if media_inherit_permissions?
          Hyrax::PermissionTemplateApplicator.apply(permission_template).to(model: member)
          member.save!
          InheritPermissionsJob.perform_later(member.id)
        else
          puts "+++++++++++++++++++++++++++++++++++++++++++++++"
          puts "+++++++++++++++++++++++++++++++++++++++++++++++"
          Rails.logger.info("[AddMemberObjects] collection=#{self.id} member=#{member.id}, thumbnail=#{member.thumbnail_id}")
          puts "[AddMemberObjects] collection=#{self.id} member=#{member.id}, thumbnail=#{member.thumbnail_id}"
          Rails.logger.info("[AddMemberObjects] member=#{member.id}about to save!")
          puts "[AddMemberObjects] member=#{member.id} about to save!"
          member.save!
          Rails.logger.info("[AddMemberObjects] Successfully added member #{member.id} to collection #{self.id}")
          puts "[AddMemberObjects] Successfully added member #{member.id} to collection #{self.id}"
          s = SolrDocument.find(member.id)
          Rails.logger.info("[AddMemberObjects] SolrDocument for member #{member.id} has thumbnail #{s["thumbnail_path_ss"]} and member_of_collection_ids #{s['member_of_collection_ids_ssim']}")
          puts "[AddMemberObjects] SolrDocument for member #{member.id} has thumbnail #{s["thumbnail_path_ss"]} and member_of_collection_ids #{s['member_of_collection_ids_ssim']}"
          puts "+++++++++++++++++++++++++++++++++++++++++++++++"
          puts "+++++++++++++++++++++++++++++++++++++++++++++++"
        end
        UpdateWorkIndexJob.perform_later(object_id) if object_id.present?
      end
      member
    end
  end

  def remove_member_objects(member_ids)
    member_ids.each do |id|
      work = ActiveFedora::Base.find(id)
      work.member_of_collections.delete self
      if media_inherit_permissions?
        remove_team_access_grants(work)
      end
      work.save!
      object_id = work.physical_object_id&.first
      UpdateWorkIndexJob.perform_later(object_id) if object_id.present?
      if media_inherit_permissions?
        InheritPermissionsJob.perform_later(work.id)
      end
    end
  end

  def remove_team_access_grants(work)
    return unless team? || project?
    work.edit_groups -= [managers_group.name, editors_group.name]
    work.read_groups -= [viewers_group.name]
    work.download_groups -= [downloaders_group.name]
    reapply_org_team_access(work)
  end

  def reapply_org_team_access(work)
    # re-apply org-link team access if the media belongs to the same org-linked team
    return unless self.organization.present?
    return unless work.organizations_team_ids.include? self.id
    groups = []
    DEFAULT_GROUP_ROLES.each do |role|
      groups.push(self.id + '_' + role)
    end
    work.read_groups = (work.read_groups + groups).uniq
  end

  def membership_of(user)
    membership_list = []
    membership_list << 'Manager' if managers.include?(user)
    membership_list << 'Editor' if editors.include?(user)
    membership_list << 'Depositor' if depositors.include?(user)
    membership_list << 'Viewer' if viewers.include?(user)
    membership_list << 'Downloader' if downloaders.include?(user)
    membership_list
  end

  def child_projects
    ActiveFedora::Base.where("member_of_collection_ids_ssim:#{id}").select{ |c| c.class == Collection && c.project? }
  end

  # override Hyrax::CollectionBehavior method to allow collection types to be changed
  def collection_type_gid=(new_collection_type_gid)
    new_collection_type_gid = new_collection_type_gid&.to_s
    new_collection_type = Hyrax::CollectionType.find_by_gid!(new_collection_type_gid)
    super(new_collection_type_gid)
    @collection_type = new_collection_type
    collection_type_gid
  end

  # Temporary View Access Link methods
  def temporary_links
    TemporaryCollectionAccessLink.where(collection_id: id)
  end

  def active_temporary_links
    temporary_links.where('expires_at > ?', DateTime.now)
  end

  # modality options for creating new media in the collection
  # override this to allow only certain modalities
  def media_modalities
    Morphosource::ModalitiesService.new.select_all_options
  end

  def search_builder_class
    Morphosource::Users::MyMediaSearchBuilder
  end

  def media_docs
    Morphosource::SolrService.new.get_docs("member_of_collection_ids_ssim:#{id} AND has_model_ssim:Media")
  end

  def media
    Media.where("member_of_collection_ids_ssim:#{id}")
  end

  # Faster than ActiveFedora::Base.exists? for String ID by bypassing ActiveFedora::Base.find().
  # @param [ActiveFedora::Base, String, Hash] object, id or hash of conditions
  # @return [Boolean] true if object having the id or matching the conditions exists in the repository
  def self.exists?(conditions)
    conditions = { id: conditions } if conditions.is_a? String
    super(conditions)
  end

  # Finds the first record matching the specified conditions, or nil if no record found.
  # Similar to ActiveRecord find_by method.
  #
  # Collection.find_by(id: "123456789")
  # Collection.find_by("human_readable_type_tesim" => "Project")
  # Collection.find_by( [ "human_readable_type_tesim:Project", "id:123456789" ] )
  # Collection.find_by( { ""human_readable_type_tesim" => "Project", id: "123456789" } )
  #
  # @param [Hash, String, Array] One or more conditions, using Solr field names
  # @return [::Collection, nil] First matching record object or nil if none found
  def self.find_by(arg, *args)
    where(arg, *args).take
  end

  def can_manage_devices?
    false
  end

  private

    def add_depositor_to_managers
      user = User.find_by(ms_id: depositor)
      unless managers_group.users.include? user
        managers_group.users << user
        managers_group.save
      end
    end

    def destroy_default_groups
      user_groups.compact.each(&:destroy)
    end

    def add_date_uploaded
      self.date_uploaded = date_uploaded.nil? ? Time.now : date_uploaded
    end

    # reindex child projects, media, and physical objects
    def reindex_collection_members
      members = ActiveFedora::Base.where("member_of_collection_ids_ssim:#{id} OR media_member_of_team_ids_ssim:#{id} OR media_member_of_project_ids_ssim:#{id}")
      members.each(&:update_index)
    end
end
