# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base

  # properties must go before include Morphosource::FileSetBehavior
  property :accessibility, predicate: ::RDF::URI.new("https://www.morphosource.org/terms/accessibility")
  property :mime_type_of_remote, predicate: ::RDF::URI.new("https://www.morphosource.org/terms/mimeTypeOfRemote"), multiple: false
  property :digest, predicate: ::RDF::URI.new("https://www.morphosource.org/terms/digest"), multiple: false

  include Morphosource::FileSetBehavior

  # MS_CUSTOMIZATION : override FileSetIndexer
  #self.indexer = ::FileSetIndexer
  self.indexer = ::MsFileSetIndexer

  # for all file types
  delegate(
    :crc32,
    to: :characterization_proxy
  )

  # for images
  delegate(
    :bits_per_sample,
    :color_space,
    :compression,
    :focal_length,
    :aperture_value,
    :iso_speed_ratings,
    :shutter_speed,
    to: :characterization_proxy
    )

  # for dicom
  delegate(
    :spacing_between_slices,
    :modality,
    :secondary_capture_device_manufacturer,
    :secondary_capture_device_software_vers,
    :file_type_extension,
    :image_type,
    :study_date,
    :series_date,
    :content_date,
    :study_time,
    :series_time,
    :content_time,
    :accession_number,
    :instance_number,
    :image_position_patient,
    :image_orientation_patient,
    :samples_per_pixel,
    :photometric_interpretation,
    :rows,
    :columns,
    :pixel_spacing,
    :slice_thickness,
    :bits_allocated,
    :bits_stored,
    :high_bit,
    :pixel_representation,
    :window_center,
    :window_width,
    :rescale_intercept,
    :rescale_slope,
    :window_center_and_width_explanation,

    :exposure_time,
    :pixel_spacing_calibration_type,
    :contrast_frame_averaging,
    :images_in_acquisition,
    :KVP,
    :generator_power,
    :x_ray_tube_current,
    :container_description,
    :generator_id,
    :detector_description,
    :distance_source_to_patient,
    :distance_source_to_detector,
    :anode_target_material,
    :spiral_pitch_factor,
    :number_of_series_related_instances,
    to: :characterization_proxy
  )

  # for mesh
  delegate(
    :point_count,
    :face_count,
    :edges_per_face,
    :bounding_box_x,
    :bounding_box_y,
    :bounding_box_z,
    :centroid_x,
    :centroid_y,
    :centroid_z,
    :color_format,
    :normals_format,
    :has_uv_space,
    :vertex_color,
    to: :characterization_proxy
  )

  # for zip archive contents
  delegate(
    :contents_mime_type,
    :contents_file_name,
    :contents_file_size,
    :contents_accepted_file_count,
    to: :characterization_proxy
  )

  def media?
    false
  end

  def processing_event?
    false
  end

  def set_mime_type_if_remote
    if is_remote_backed?
      self.mime_type_of_remote = characterization_proxy.mime_type
      characterization_proxy.mime_type = "message/external-body; access-type=URL; URL=\"#{import_url}\""
      characterization_proxy.save
      self.save
    end
  end

  def is_remote_backed?
    # todo: might need additional condition to distinguish remoted-backed from browse everywhere uploads
    import_url&.match(/^https?:\/\//).present?
  end
end
