# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base

  include ::Hyrax::FileSetBehavior

  self.indexer = ::FileSetIndexer

  delegate(:bits_per_sample, to: :characterization_proxy)

end
