# Automatically generates release for pull request to master with tag
name: Generate Release From PR
on:
  pull_request:
    types: [closed]
    branches: [master]
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Tag
        uses: nitinses/semver-release-action@v1.0.8
        with:
          release_branch: master
          generate_release_notes: true
          tag_format: "%major%.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      